name: Grammdb CI

on:
  pull_request:
    branches: ["main"]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.12
            3.13
      - name: Install Hatch
        run: pipx install hatch
      - name: Run Hatch CI
        run: hatch run ci
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.12
            3.13
      - name: Install Hatch
        run: pipx install hatch
      - name: Run Hatch CI
        run: hatch run ci
